In [1]:
# Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Import CSVs
salary_file = "./resources/teacher-salary-2017.csv"
academic_file = "./resources/academic-performance-2017.csv"

In [3]:
# Convert CSVs to Dataframes
salary_df = pd.read_csv(salary_file)
academic_df = pd.read_csv(academic_file)

In [4]:
# Show initial salary DataFrame
salary_df

,State,1969-70,1979-80,1989-90,1999-2000,2009-10,2015-16,2016-17,1969-70.1,1979-80.1,1989-90.1,1999-2000.1,2009-10.1,2015-16.1,2016-17.1
0,Alabama,"6,818","13,060","24,828","36,689","47,571","48,518","48,868","43,797","40,821","47,448","52,588","53,260","49,410","48,868"
1,Alaska,"10,560","27,210","43,153","46,462","59,672","67,443","68,138","67,834","85,050","82,468","66,597","66,809","68,684","68,138"
2,Arizona,"8,711","15,054","29,402","36,902","46,952","47,218","47,403","55,957","47,054","56,189","52,894","52,567","48,087","47,403"
3,Arkansas,"6,307","12,299","22,352","33,386","46,700","48,218","48,616","40,514","38,443","42,716","47,854","52,285","49,105","48,616"
4,California,"10,315","18,020","37,998","47,680","68,203","77,179","78,711","66,261","56,325","72,616","68,342","76,360","78,599","78,711"
5,Colorado,"7,761","16,205","30,758","38,163","49,202","46,155","46,506","49,854","50,652","58,780","54,701","55,086","47,004","46,506"
6,Connecticut,"9,262","16,229","40,461","51,780","64,350","72,013","72,561","59,496","50,727","77,323","74,219","72,046","73,338","72,561"
7,Delaware,"9,015","16,148","33,377","44,435","57,080","59,960","60,214","57,910","50,473","63,785","63,691","63,907","61,063","60,214"
8,District of Columbia,"10,285","22,190","38,402","47,076","64,548","75,810","76,131","66,068","69,359","73,388","67,477","72,268","77,205","76,131"
9,Florida,"8,412","14,149","28,803","36,722","46,708","49,199","49,407","54,036","44,225","55,044","52,636","52,294","50,104","49,407"
10,Georgia,"7,276","13,853","28,006","41,023","53,112","54,190","54,602","46,739","43,300","53,521","58,801","59,464","55,187","54,602"
11,Hawaii,"9,453","19,920","32,047","40,578","55,063","57,431","57,674","60,723","62,264","61,244","58,163","61,648","58,487","57,674"
12,Idaho,"6,890","13,611","23,861","35,547","46,283","46,122","47,504","44,259","42,544","45,600","50,952","51,818","46,970","47,504"
13,Illinois,"9,569","17,601","32,794","46,486","62,077","61,342","61,602","61,469","55,015","62,671","66,631","69,501","62,470","61,602"
14,Indiana,"8,833","15,599","30,902","41,850","49,986","50,715","50,554","56,741","48,757","59,055","59,986","55,964","51,648","50,554"
15,Iowa,"8,355","15,203","26,747","35,678","49,626","54,416","55,443","53,670","47,520","51,115","51,139","55,561","55,417","55,443"
16,Kansas,"7,612","13,690","28,744","34,981","46,657","47,755","47,984","48,897","42,791","54,931","50,140","52,237","48,633","47,984"
17,Kentucky,"6,953","14,520","26,292","36,380","49,543","52,134","52,339","44,664","45,385","50,245","52,146","55,468","53,093","52,339"
18,Louisiana,"7,028","13,760","24,300","33,109","48,903","49,745","50,000","45,146","43,009","46,439","47,457","54,752","50,660","50,000"
19,Maine,"7,572","13,071","26,881","35,561","46,106","50,498","51,077","48,640","40,856","51,371","50,972","51,620","51,427","51,077"
20,Maryland,"9,383","17,558","36,319","44,048","63,971","66,456","66,961","60,274","54,881","69,408","63,137","71,622","67,678","66,961"
21,Massachusetts,"8,764","17,253","34,712","46,580","69,273","76,981","77,804","56,297","53,927","66,336","66,766","77,558","78,397","77,804"
22,Michigan,"9,826","19,663","37,072","49,044","57,958","62,028","62,200","63,119","61,460","70,847","70,298","64,890","63,169","62,200"
23,Minnesota,"8,658","15,912","32,190","39,802","52,431","56,913","57,346","55,617","49,736","61,517","57,051","58,702","57,960","57,346"
24,Mississippi,"5,798","11,850","24,292","31,857","45,644","42,744","42,925","37,245","37,039","46,423","45,662","51,103","43,530","42,925"
25,Missouri,"7,799","13,682","27,094","35,656","45,317","47,957","48,293","50,099","42,766","51,778","51,108","50,737","48,839","48,293"
26,Montana,"7,606","14,537","25,081","32,121","45,759","51,034","51,422","48,859","45,438","47,931","46,041","51,232","51,973","51,422"
27,Nebraska,"7,375","13,516","25,522","33,237","46,227","51,386","52,338","47,375","42,247","48,774","47,641","51,756","52,331","52,338"
28,Nevada,"9,215","16,295","30,590","39,390","51,524","56,943","57,376","59,195","50,933","58,459","56,460","57,686","57,990","57,376"
29,New Hampshire,"7,771","13,017","28,986","37,734","51,443","56,616","57,253","49,919","40,687","55,394","54,086","57,595","57,657","57,253"
30,New Jersey,"9,130","17,161","35,676","52,015","65,130","69,330","69,623","58,649","53,640","68,179","74,556","72,919","70,605","69,623"
31,New Mexico,"7,796","14,887","24,756","32,554","46,258","47,163","47,500","50,079","46,532","47,310","46,662","51,790","48,031","47,500"
32,New York,"10,336","19,812","38,925","51,020","71,633","79,152","79,637","66,396","61,926","74,388","73,130","80,200","80,608","79,637"
33,North Carolina,"7,494","14,117","27,883","39,404","46,850","47,941","49,837","48,139","44,125","53,286","56,480","52,453","48,823","49,837"
34,North Dakota,"6,696","13,263","23,016","29,863","42,964","50,472","51,618","43,013","41,456","43,985","42,804","48,102","51,400","51,618"
35,Ohio,"8,300","15,269","31,218","41,436","55,958","56,441","57,000","53,317","47,726","59,659","59,393","62,650","57,479","57,000"
36,Oklahoma,"6,882","13,107","23,070","31,298","47,691","45,276","45,245","44,208","40,968","44,088","44,861","53,395","46,109","45,245"
37,Oregon,"8,818","16,266","30,840","42,336","55,224","60,359","61,631","56,644","50,842","58,937","60,683","61,829","61,469","61,631"
38,Pennsylvania,"8,858","16,515","33,338","48,321","59,156","65,151","65,863","56,901","51,621","63,711","69,261","66,231","66,349","65,863"
39,Rhode Island,"8,776","18,002","36,057","47,041","59,686","66,197","66,477","56,375","56,269","68,907","67,427","66,824","67,415","66,477"
40,South Carolina,"6,927","13,063","27,217","36,081","47,508","48,769","48,598","44,497","40,831","52,013","51,717","53,190","49,666","48,598"
41,South Dakota,"6,403","12,348","21,300","29,071","38,837","42,025","42,668","41,131","38,596","40,705","41,669","43,482","42,798","42,668"
42,Tennessee,"7,050","13,972","27,052","36,328","46,290","48,217","48,456","45,287","43,672","51,698","52,071","51,826","49,104","48,456"
43,Texas,"7,255","14,132","27,496","37,567","48,261","51,890","52,575","46,604","44,172","52,546","53,847","54,033","52,845","52,575"
44,Utah,"7,644","14,909","23,686","34,946","45,885","46,887","47,244","49,103","46,601","45,265","50,090","51,373","47,749","47,244"
45,Vermont,"7,968","12,484","29,012","37,758","49,084","58,901","60,187","51,184","39,021","55,443","54,121","54,954","59,984","60,187"
46,Virginia,"8,070","14,060","30,938","38,744","50,015","50,834","51,049","51,839","43,947","59,124","55,534","55,997","51,769","51,049"
47,Washington,"9,225","18,820","30,457","41,043","53,003","53,738","54,147","59,259","58,825","58,205","58,829","59,342","54,727","54,147"
48,West Virginia,"7,650","13,710","22,842","35,009","45,959","45,622","45,701","49,141","42,853","43,652","50,180","51,456","46,461","45,701"
49,Wisconsin,"8,963","16,006","31,921","41,153","51,264","54,115","54,998","57,576","50,030","61,003","58,987","57,395","55,110","54,998"
50,Wyoming,"8,232","16,012","28,141","34,127","55,861","58,140","58,650","52,880","50,048","53,779","48,916","62,542","59,209","58,650"

In [5]:
# # Show initial academic DataFrame
# academic_df

In [6]:
# Reduce size of salary_df to only have state and year
salary_data = {'us_state':salary_df['State'],
              'salary':salary_df['2016-17.1']}
salary_df = pd.DataFrame(salary_data)

In [7]:
# Rename Jurisdiction to State in academic_df
academic_data = {'us_state':academic_df['Jurisdiction'],
                'at_or_above_basic':academic_df['AB'],
                'at_or_above_proficient':academic_df['AP']}
academic_df = pd.DataFrame(academic_data)

In [8]:
# Show salary_df after updates
salary_df['salary']=salary_df['salary'].str.replace(',','')
salary_df['us_state'] = salary_df.copy()['us_state'].str.strip()
salary_df

                us_state salary
0                Alabama  48868
1                 Alaska  68138
2                Arizona  47403
3               Arkansas  48616
4             California  78711
5               Colorado  46506
6            Connecticut  72561
7               Delaware  60214
8   District of Columbia  76131
9                Florida  49407
10               Georgia  54602
11                Hawaii  57674
12                 Idaho  47504
13              Illinois  61602
14               Indiana  50554
15                  Iowa  55443
16                Kansas  47984
17              Kentucky  52339
18             Louisiana  50000
19                 Maine  51077
20              Maryland  66961
21         Massachusetts  77804
22              Michigan  62200
23             Minnesota  57346
24           Mississippi  42925
25              Missouri  48293
26               Montana  51422
27              Nebraska  52338
28                Nevada  57376
29         New Hampshire  57253
30            New Jersey  69623
31            New Mexico  47500
32              New York  79637
33        North Carolina  49837
34          North Dakota  51618
35                  Ohio  57000
36              Oklahoma  45245
37                Oregon  61631
38          Pennsylvania  65863
39          Rhode Island  66477
40        South Carolina  48598
41          South Dakota  42668
42             Tennessee  48456
43                 Texas  52575
44                  Utah  47244
45               Vermont  60187
46              Virginia  51049
47            Washington  54147
48         West Virginia  45701
49             Wisconsin  54998
50               Wyoming  58650

In [9]:
# show academic_df after updates
performances_df= academic_df.drop([53,1])
performancer_df= performances_df.drop([2,2])
performance_df= performancer_df.drop([30,3])
performance_df

                us_state  at_or_above_basic at_or_above_proficient
0          Massachusetts                 87                     53
4             New Jersey                 87                     50
5                Wyoming                 89                     51
6                Indiana                 86                     48
7                Florida                 88                     48
8               Nebraska                 85                     49
9          New Hampshire                 85                     48
10          North Dakota                 85                     46
11                  Iowa                 83                     46
12                  Utah                 81                     45
13            Washington                 80                     42
14          Pennsylvania                 80                     44
15          South Dakota                 83                     43
16                Kansas                 82                     42
17        North Carolina                 81                     42
18                 Texas                 82                     41
19                  Ohio                 81                     41
20               Vermont                 81                     42
21               Montana                 83                     41
22              Colorado                 80                     42
23              Maryland                 78                     42
24             Wisconsin                 79                     42
25                 Idaho                 81                     40
26                 Maine                 81                     40
27              Missouri                 79                     40
28           Connecticut                 79                     40
29              Kentucky                 80                     40
31              Illinois                 76                     39
32                Hawaii                 79                     38
33          Rhode Island                 79                     39
34              Oklahoma                 80                     35
35             Tennessee                 77                     36
36               Georgia                 77                     35
37              Delaware                 77                     36
38         West Virginia                 78                     35
39              Michigan                 75                     36
40              New York                 76                     35
41           Mississippi                 77                     31
42               Arizona                 73                     34
43        South Carolina                 75                     32
44              Arkansas                 75                     33
45                Oregon                 73                     33
46            California                 71                     31
47               Alabama                 73                     31
48                Nevada                 73                     31
49  District of Columbia                 69                     32
50                Alaska                 71                     32
51            New Mexico                 69                     27
52             Louisiana                 71                     27

In [10]:
# Merge DataFrames for all states that match
final_data = {'us_state':salary_df['us_state'],
              'salary':salary_df['salary'],
              'at_or_above_basic':academic_df['at_or_above_basic'],
              'at_or_above_proficient':academic_df['at_or_above_proficient']
             }
final_df = pd.DataFrame(final_data)

In [11]:
# Drop NaN values
final_df = final_df[final_df['us_state'].notna()]

In [12]:
# Display final df
final_df

                us_state salary  at_or_above_basic at_or_above_proficient
0                Alabama  48868                 87                     53
1                 Alaska  68138                 86                     53
2                Arizona  47403                 91                     51
3               Arkansas  48616                 87                     50
4             California  78711                 87                     50
5               Colorado  46506                 89                     51
6            Connecticut  72561                 86                     48
7               Delaware  60214                 88                     48
8   District of Columbia  76131                 85                     49
9                Florida  49407                 85                     48
10               Georgia  54602                 85                     46
11                Hawaii  57674                 83                     46
12                 Idaho  47504                 81                     45
13              Illinois  61602                 80                     42
14               Indiana  50554                 80                     44
15                  Iowa  55443                 83                     43
16                Kansas  47984                 82                     42
17              Kentucky  52339                 81                     42
18             Louisiana  50000                 82                     41
19                 Maine  51077                 81                     41
20              Maryland  66961                 81                     42
21         Massachusetts  77804                 83                     41
22              Michigan  62200                 80                     42
23             Minnesota  57346                 78                     42
24           Mississippi  42925                 79                     42
25              Missouri  48293                 81                     40
26               Montana  51422                 81                     40
27              Nebraska  52338                 79                     40
28                Nevada  57376                 79                     40
29         New Hampshire  57253                 80                     40
30            New Jersey  69623                 79                     40
31            New Mexico  47500                 76                     39
32              New York  79637                 79                     38
33        North Carolina  49837                 79                     39
34          North Dakota  51618                 80                     35
35                  Ohio  57000                 77                     36
36              Oklahoma  45245                 77                     35
37                Oregon  61631                 77                     36
38          Pennsylvania  65863                 78                     35
39          Rhode Island  66477                 75                     36
40        South Carolina  48598                 76                     35
41          South Dakota  42668                 77                     31
42             Tennessee  48456                 73                     34
43                 Texas  52575                 75                     32
44                  Utah  47244                 75                     33
45               Vermont  60187                 73                     33
46              Virginia  51049                 71                     31
47            Washington  54147                 73                     31
48         West Virginia  45701                 73                     31
49             Wisconsin  54998                 69                     32
50               Wyoming  58650                 71                     32

In [13]:
connection_string = "postgres:0217@localhost:5432/Student Performance"
engine = create_engine(f'postgresql://{connection_string}')

In [14]:
# Confirm tables
engine.table_names()

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)

In [15]:
salary_df.to_sql(name='salary', con=engine, if_exists='append', index=False)

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)

In [16]:
performance_df.to_sql(name='performance', con=engine, if_exists='append', index=False)

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)